buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies { classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT' }
}
plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}
ext.forgeTarget = [minecraftVersion: '1.21.9', minecraftVersionRange: '[1.21.9,1.21.10)',
        forgeVersion: '59.0.5', forgeVersionRange: '[59,60)', sourceEra: 'record', hudLayer: 'eventbus7-standalone']
apply from: "${rootDir}/platform/forge-common/modern-target.gradle"
