buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies { classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT' }
}
plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}
ext.forgeTarget = [minecraftVersion: '1.21.7', minecraftVersionRange: '[1.21.7,1.21.8)',
        forgeVersion: '57.0.3', forgeVersionRange: '[57,58)', sourceEra: 'eventbus7', hudLayer: 'mixin']
apply from: "${rootDir}/platform/forge-common/modern-target.gradle"
